# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161026_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaitem',
            name='answer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
